
query AdminPanelKey {
    adminPanelKey {
        code
        success
        message
        data
    }
}

query CheckAdmin {
    checkAdmin {
        code
        success
        message
        data
    }
}

mutation AdminLogin($username: String!, $password: String!){
    adminLogin(username: $username, password: $password) {
        code
        success
        message
        data
    }
}

mutation AdminLogout {
    adminLogout {
        code
        success
        message
        data
    }
}

# mutation CreateAT {
#     createAT {
#         code
#         success
#         message
#         data
#     }
# }