import * as Types from '../../../types/__generated__/graphql';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type SiteConfigFieldsFragment = { __typename: 'SiteConfigType', opening_at: string, closing_at: string, support_email: string, phone_number: string, min_duration: number, timezone: string, c_country: string };

export type PublicConfigQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type PublicConfigQuery = { publicConfig: { __typename: 'PublicConfigResponseType', code: number, success: boolean, message: string, data: Array<{ __typename: 'PublicConfigType', opening_at: string, closing_at: string, support_email: string, phone_number: string, min_duration: number, timezone: string, c_country: string } | null> } };

export type GetSiteConfigQueryVariables = Types.Exact<{
  id: Types.Scalars['ID']['input'];
}>;


export type GetSiteConfigQuery = { siteConfig: { __typename: 'SiteConfigResponseType', code: number, success: boolean, message: string, data: Array<{ __typename: 'SiteConfigType', opening_at: string, closing_at: string, support_email: string, phone_number: string, min_duration: number, timezone: string, c_country: string } | null> } };

export type UpdateSiteConfigMutationVariables = Types.Exact<{
  id: Types.Scalars['ID']['input'];
  data: Types.SiteConfigUpdateInput;
}>;


export type UpdateSiteConfigMutation = { updateSiteConfig: { __typename: 'SiteConfigResponseType', code: number, success: boolean, message: string, data: Array<{ __typename: 'SiteConfigType', opening_at: string, closing_at: string, support_email: string, phone_number: string, min_duration: number, timezone: string, c_country: string } | null> } };

export const SiteConfigFieldsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"SiteConfigFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"SiteConfigType"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"opening_at"}},{"kind":"Field","name":{"kind":"Name","value":"closing_at"}},{"kind":"Field","name":{"kind":"Name","value":"support_email"}},{"kind":"Field","name":{"kind":"Name","value":"phone_number"}},{"kind":"Field","name":{"kind":"Name","value":"min_duration"}},{"kind":"Field","name":{"kind":"Name","value":"timezone"}},{"kind":"Field","name":{"kind":"Name","value":"c_country"}}]}}]} as unknown as DocumentNode<SiteConfigFieldsFragment, unknown>;
export const PublicConfigDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"PublicConfig"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"publicConfig"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"success"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"data"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"opening_at"}},{"kind":"Field","name":{"kind":"Name","value":"closing_at"}},{"kind":"Field","name":{"kind":"Name","value":"support_email"}},{"kind":"Field","name":{"kind":"Name","value":"phone_number"}},{"kind":"Field","name":{"kind":"Name","value":"min_duration"}},{"kind":"Field","name":{"kind":"Name","value":"timezone"}},{"kind":"Field","name":{"kind":"Name","value":"c_country"}}]}}]}}]}}]} as unknown as DocumentNode<PublicConfigQuery, PublicConfigQueryVariables>;
export const GetSiteConfigDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetSiteConfig"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"siteConfig"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"success"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"data"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"SiteConfigFields"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"SiteConfigFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"SiteConfigType"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"opening_at"}},{"kind":"Field","name":{"kind":"Name","value":"closing_at"}},{"kind":"Field","name":{"kind":"Name","value":"support_email"}},{"kind":"Field","name":{"kind":"Name","value":"phone_number"}},{"kind":"Field","name":{"kind":"Name","value":"min_duration"}},{"kind":"Field","name":{"kind":"Name","value":"timezone"}},{"kind":"Field","name":{"kind":"Name","value":"c_country"}}]}}]} as unknown as DocumentNode<GetSiteConfigQuery, GetSiteConfigQueryVariables>;
export const UpdateSiteConfigDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"UpdateSiteConfig"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"data"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"SiteConfigUpdateInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"updateSiteConfig"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}},{"kind":"Argument","name":{"kind":"Name","value":"data"},"value":{"kind":"Variable","name":{"kind":"Name","value":"data"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"success"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"data"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"SiteConfigFields"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"SiteConfigFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"SiteConfigType"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"opening_at"}},{"kind":"Field","name":{"kind":"Name","value":"closing_at"}},{"kind":"Field","name":{"kind":"Name","value":"support_email"}},{"kind":"Field","name":{"kind":"Name","value":"phone_number"}},{"kind":"Field","name":{"kind":"Name","value":"min_duration"}},{"kind":"Field","name":{"kind":"Name","value":"timezone"}},{"kind":"Field","name":{"kind":"Name","value":"c_country"}}]}}]} as unknown as DocumentNode<UpdateSiteConfigMutation, UpdateSiteConfigMutationVariables>;